[package]
name        = "alor_http"
version     = "0.1.0"
edition     = "2021"
license     = "MIT"

[dependencies]
tokio       = { version = "1", features = ["rt-multi-thread", "macros"] }
reqwest     = { version = "0.12", features = ["json", "rustls-tls"] }
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
chrono      = { version = "0.4", default-features = false, features = ["clock"] }
uuid        = { version = "1", features = ["v4"] }
thiserror   = "1"
url         = "2"
wiremock = "0.6"
